version = 1

[[analyzers]]
  name = "python"

  [analyzers.meta]
    additional_builtins = ["_", "pretty_output"]
    runtime_version = "3.x.x"

[[analyzers]]
  name = "secrets"

[[transformers]]
  name = "ruff"
