[project]
  dependencies = ["matplotlib>=3.10.8", "tensorflow>=2.20.0"]
  description = "Add your description here"
  name = "autoencoder"
  readme = "README.md"
  requires-python = ">=3.13,<3.14"
  version = "0.0.1"
