[project]
name = "autoencoder"
version = "0.0.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13,<3.14"
dependencies = [
    "matplotlib>=3.10.8",
    "tensorflow>=2.20.0",
]
